In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [17]:
import pandas as pd

In [13]:
df = pd.read_csv("./datasets/data_titanic3.csv")

In [14]:
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

     age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.00      0      0   24160  211.3375       B5        S    2    NaN   
1   0.92      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.00      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.00      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [15]:
df.shape

(1309, 14)

In [16]:
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881138     0.498854     0.385027   
std       0.837836     0.486055    14.413493     1.041658     0.865560   
min       1.000000     0.000000     0.170000     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [17]:
df.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [18]:
selected_cols = ['survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'fare','embarked']

In [19]:
sdf = df[selected_cols]

In [20]:
sdf

survived                                             name     sex  \
0            1                    Allen, Miss. Elisabeth Walton  female   
1            1                   Allison, Master. Hudson Trevor    male   
2            0                     Allison, Miss. Helen Loraine  female   
3            0             Allison, Mr. Hudson Joshua Creighton    male   
4            0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   
...        ...                                              ...     ...   
1304         0                             Zabour, Miss. Hileni  female   
1305         0                            Zabour, Miss. Thamine  female   
1306         0                        Zakarian, Mr. Mapriededer    male   
1307         0                              Zakarian, Mr. Ortin    male   
1308         0                               Zimmerman, Mr. Leo    male   

        age  sibsp  parch      fare embarked  
0     29.00      0      0  211.3375        S  
1      0.92      1      2  151.5500        S  
2      2.00      1      2  151.5500        S  
3     30.00      1      2  151.5500        S  
4     25.00      1      2  151.5500        S  
...     ...    ...    ...       ...      ...  
1304  14.50      1      0   14.4542        C  
1305    NaN      1      0   14.4542        C  
1306  26.50      0      0    7.2250        C  
1307  27.00      0      0    7.2250        C  
1308  29.00      0      0    7.8750        S  

[1309 rows x 8 columns]

In [21]:
import numpy as np

In [22]:
scalar = 18

In [23]:
scalar_np = np.array(18)

In [24]:
scalar_np.shape

()

In [26]:
type(scalar), type(scalar_np)

(int, numpy.ndarray)

In [27]:
vec = [1, 2, 3]
vec_np = np.array(vec)
vec_np.shape

(3,)

In [28]:
matrix_list = [[1,2,3], [4, 5, 6]]
matrix_np = np.array(matrix_list)

In [29]:
matrix_np

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
type(matrix_np), matrix_np.shape

(numpy.ndarray, (2, 3))

In [32]:
row_vec = np.array([[1,2,3]])
row_vec.shape

(1, 3)

In [33]:
col_vec = np.array([[1], [2], [3]])
col_vec.shape

(3, 1)

In [34]:
ma = np.array([[1, 2, 3], [4, 5, 6]])

In [35]:
mb = ma * 2

In [36]:
mb

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [37]:
ma + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [38]:
ma, mb

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [39]:
ma + mb

array([[ 3,  6,  9],
       [12, 15, 18]])

## 矩阵的<b>点积<b/> 与 <b>叉乘</b>
    - 点乘：对应元素相乘
    - 叉乘：矩阵乘法

In [40]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [41]:
m1.shape, m2.shape

((2, 3), (3, 2))

In [42]:
m1 * m2

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [43]:
ma,mb

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [44]:
ma * mb # === np.multiply(ma, mb)

array([[ 2,  8, 18],
       [32, 50, 72]])

In [46]:
np.multiply(ma, mb)

array([[ 2,  8, 18],
       [32, 50, 72]])

In [47]:
ma

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.add(ma, 1), np.subtract(ma, 1), np.multiply(ma, 2)

(array([[2, 3, 4],
        [5, 6, 7]]),
 array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [51]:
ma

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
np.multiply(ma, 2), np.dot(ma, 2)

(array([[ 2,  4,  6],
        [ 8, 10, 12]]),
 array([[ 2,  4,  6],
        [ 8, 10, 12]]))

In [56]:
m1, m2

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [57]:
np.matmul(m1, m2)

array([[22, 28],
       [49, 64]])

In [58]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
m1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
m1.shape, m1.T.shape

((2, 3), (3, 2))

In [61]:
np.transpose(m1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [62]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
m1.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### 读取数据

In [2]:
from sklearn.datasets import load_boston

d:\programdata\anaconda3\envs\tf1.15\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [14]:
house_data = load_boston()
type(house_data)

sklearn.utils.Bunch

In [15]:
house_np = house_data.data
target_np = house_data.target

In [16]:
house_np.shape, target_np.shape

((506, 13), (506,))

In [21]:
house_df = pd.DataFrame(house_np)
house_df.head()

0     1     2    3      4      5     6       7    8      9     10  \
0  0.00632  18.0  2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1  0.02731   0.0  7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2  0.02729   0.0  7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3  0.03237   0.0  2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4  0.06905   0.0  2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   

       11    12  
0  396.90  4.98  
1  396.90  9.14  
2  392.83  4.03  
3  394.63  2.94  
4  396.90  5.33

In [23]:
house_data.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [25]:
x = house_np.astype('float32')
y = target_np

In [55]:
x.shape, y.shape, x.dtype

((506, 13), (506,), dtype('float64'))

In [27]:
import tensorflow as tf

In [48]:
X = tf.placeholder(tf.float32, [None, 13], name='X')
Y = tf.placeholder(tf.float32, [None, 1], name='Y')

## 定义命名空间

In [100]:
with tf.name_scope('Model'):
    w = tf.Variable(tf.random_normal([13, 1], stddev=0.01), name='W', dtype='float32')
    b = tf.Variable(1.0, name='b', dtype='float32')
    
    def model(x, w, b):
        return tf.matmul(x, w) + b
    
    pred = model(X, w, b)
    

In [101]:
train_epochs = 50
learning_rate = 0.01

In [102]:
with tf.name_scope('LossFunction'):
    loss = tf.reduce_mean(tf.pow(Y - pred, 2))

In [103]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [59]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(loss)

In [67]:
from random import shuffle
shuffle([1,2,3])

In [71]:
for epoch in range(train_epochs):
    loss_sum = 0.0
    for sx, sy in zip(x, y):
        sx = sx.reshape(1, 13)
        sy = sy.reshape(1, 1)
        _,loss_ = sess.run([optimizer, loss], feed_dict={X:sx, Y:sy})
        loss_sum += loss_
    
    #xvalues, yvalues = shuffle(x, y)
    b0tmp = b.eval(session=sess)
    w0temp = w.eval(session=sess)
    loss_avg = loss_sum/len(y)
    print(f"Epoch:{epoch+1}, loss={loss_avg}, b={b0tmp}, w={w0temp}")

Epoch:1, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:2, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:3, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:4, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:5, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:6, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:7, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:8, loss=nan, b=nan, w=[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
Epoch:9, loss=nan, b=nan, w=[[nan]
 [nan

In [74]:
pd.DataFrame(x).describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

               12  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [91]:
house_df.describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.040615    0.113636    0.408240    0.069170    1.141348    1.204184   
std      0.096679    0.233225    0.251479    0.253994    0.238431    0.134627   
min      0.000071    0.000000    0.016862    0.000000    0.792181    0.682315   
25%      0.000922    0.000000    0.190249    0.000000    0.923868    1.127706   
50%      0.002883    0.000000    0.355205    0.000000    1.106996    1.189596   
75%      0.041330    0.125000    0.663490    0.000000    1.283951    1.269113   
max      1.000071    1.000000    1.016862    1.000000    1.792181    1.682315   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.706230    0.345101    0.415192    0.779079    1.963355    0.899375   
std      0.289896    0.191482    0.378576    0.321636    0.230313    0.230205   
min      0.029866    0.102720    0.043478    0.356870    1.340426    0.000807   
25%      0.463697    0.190979    0.173913    0.532443    1.851064    0.946537   
50%      0.798146    0.291669    0.217391    0.629771    2.026596    0.987039   
75%      0.968847    0.471808    1.043478    1.270992    2.148936    0.999105   
max      1.029866    1.102720    1.043478    1.356870    2.340426    1.000807   

               12  
count  506.000000  
mean     0.349146  
std      0.197049  
min      0.047737  
25%      0.191777  
50%      0.313466  
75%      0.467853  
max      1.047737

In [80]:
xdf = house_df.copy()
xdf.shape

(506, 13)

In [90]:
for i in range(13):
    width = house_df.iloc[:, i].max() - house_df.iloc[:, i].min()
    print(width)
    house_df.iloc[:, i] = house_df.iloc[:, i]/width

88.96988
100.0
27.279999999999998
1.0
0.486
5.218999999999999
97.1
10.9969
23.0
524.0
9.4
396.58
36.24


In [105]:
len(y)

506

In [106]:
for epoch in range(train_epochs):
    loss_sum = 0.0
    for sx, sy in zip(x, y):
        sx = sx.reshape(1, 13)
        sy = sy.reshape(1, 1)
        _,loss_ = sess.run([optimizer, loss], feed_dict={X:sx, Y:sy})
        loss_sum += loss_
    
    #xvalues, yvalues = shuffle(x, y)
    b0tmp = b.eval(session=sess)
    w0temp = w.eval(session=sess)
    loss_avg = loss_sum/len(y)
    print(f"Epoch:{epoch+1}, loss={loss_avg}, b={b0tmp}, w={w0temp}")

Epoch:1, loss=548.6535400760032, b=1.0, w=[[ 0.00680603]
 [-0.00597946]
 [ 0.00145867]
 [ 0.00204211]
 [ 0.0081683 ]
 [-0.00508914]
 [-0.01577436]
 [-0.0074087 ]
 [-0.01128733]
 [ 0.00764537]
 [-0.00820926]
 [ 0.01701554]
 [-0.01533323]]
Epoch:2, loss=548.6535400760032, b=1.0, w=[[ 0.00680603]
 [-0.00597946]
 [ 0.00145867]
 [ 0.00204211]
 [ 0.0081683 ]
 [-0.00508914]
 [-0.01577436]
 [-0.0074087 ]
 [-0.01128733]
 [ 0.00764537]
 [-0.00820926]
 [ 0.01701554]
 [-0.01533323]]
Epoch:3, loss=548.6535400760032, b=1.0, w=[[ 0.00680603]
 [-0.00597946]
 [ 0.00145867]
 [ 0.00204211]
 [ 0.0081683 ]
 [-0.00508914]
 [-0.01577436]
 [-0.0074087 ]
 [-0.01128733]
 [ 0.00764537]
 [-0.00820926]
 [ 0.01701554]
 [-0.01533323]]
Epoch:4, loss=548.6535400760032, b=1.0, w=[[ 0.00680603]
 [-0.00597946]
 [ 0.00145867]
 [ 0.00204211]
 [ 0.0081683 ]
 [-0.00508914]
 [-0.01577436]
 [-0.0074087 ]
 [-0.01128733]
 [ 0.00764537]
 [-0.00820926]
 [ 0.01701554]
 [-0.01533323]]
Epoch:5, loss=548.6535400760032, b=1.0, w=[[ 0.0

In [99]:
pd.DataFrame(x).describe()

0           1           2           3           4           5   \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.040615    0.113636    0.408240    0.069170    1.141348    1.204184   
std      0.096679    0.233225    0.251479    0.253994    0.238431    0.134627   
min      0.000071    0.000000    0.016862    0.000000    0.792181    0.682315   
25%      0.000922    0.000000    0.190249    0.000000    0.923868    1.127706   
50%      0.002883    0.000000    0.355205    0.000000    1.106996    1.189596   
75%      0.041330    0.125000    0.663490    0.000000    1.283951    1.269113   
max      1.000071    1.000000    1.016862    1.000000    1.792181    1.682315   

               6           7           8           9           10          11  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     0.706230    0.345101    0.415192    0.779079    1.963355    0.899375   
std      0.289896    0.191482    0.378576    0.321636    0.230313    0.230205   
min      0.029866    0.102720    0.043478    0.356870    1.340426    0.000807   
25%      0.463697    0.190979    0.173913    0.532443    1.851064    0.946537   
50%      0.798146    0.291669    0.217391    0.629771    2.026596    0.987039   
75%      0.968847    0.471808    1.043478    1.270992    2.148936    0.999105   
max      1.029866    1.102720    1.043478    1.356870    2.340426    1.000807   

               12  
count  506.000000  
mean     0.349146  
std      0.197049  
min      0.047737  
25%      0.191777  
50%      0.313466  
75%      0.467853  
max      1.047737

In [96]:
type(x)

numpy.ndarray

In [98]:
x[0, :]

array([7.10352762e-05, 1.80000000e-01, 8.46774194e-02, 0.00000000e+00,
       1.10699588e+00, 1.25981989e+00, 6.71472709e-01, 3.71922996e-01,
       4.34782609e-02, 5.64885496e-01, 1.62765957e+00, 1.00080690e+00,
       1.37417219e-01])